resources:
  - name: st-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/laurensmiers/st
      branch: master

jobs:
  - name: st-job
    public: true
    plan:
      - get: st-git
        trigger: true
      - task: st-make
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-hub-username))/st-builder
          inputs:
            - name: st-git
          run:
            path: make
            args:
              - -C
              - ./st-git
